package server




















































































































}	log.Println("Task Service stopped")	}		log.Fatalf("Server forced to shutdown: %v", err)	if err := srv.Shutdown(ctx); err != nil {	// Shutdown server	}		redisClient.Close()	if redisClient != nil {	// Close Redis connection	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)	// Create shutdown context with timeout	log.Println("Shutting down Task Service...")	<-quit	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)	quit := make(chan os.Signal, 1)	// Wait for interrupt signal for graceful shutdown	}()		}			log.Fatalf("Failed to start server: %v", err)		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {		log.Printf("Task Service starting on port %s", cfg.Port)	go func() {	// Start server in goroutine	}		IdleTimeout:  60 * time.Second,		WriteTimeout: 15 * time.Second,		ReadTimeout:  15 * time.Second,		Handler:      router,		Addr:         ":" + cfg.Port,	srv := &http.Server{	// Create HTTP server	routes.Setup(router, taskController, authClient)	// Setup routes	router.Use(middleware.CORS())	router.Use(middleware.Logger())	router.Use(gin.Recovery())	router := gin.New()	// Initialize router	taskController := controllers.NewTaskController(taskService)	// Initialize controllers	taskService := services.NewTaskService(taskRepo, redisClient)	// Initialize services	taskRepo := repositories.NewTaskRepository(db)	// Initialize repositories	authClient := services.NewAuthClient(cfg.AuthServiceURL)	// Initialize HTTP client for auth service	redisClient := config.InitRedis(cfg)	// Initialize Redis (optional)	}		log.Fatalf("Failed to migrate database: %v", err)	if err := db.AutoMigrate(&models.Task{}); err != nil {	// Auto migrate models	}		log.Fatalf("Failed to connect to database: %v", err)	if err != nil {	db, err := config.InitDB(cfg)	// Initialize database	}		gin.SetMode(cfg.GinMode)	if cfg.GinMode != "" {	// Set Gin mode	cfg := config.Load()	// Load configurationfunc main() {// @name Authorization// @in header// @securityDefinitions.apikey BearerAuth// @BasePath /api/v1// @host localhost:8082// @description Task Management Service for Prime Trade// @version 1.0// @title Prime Trade Task Service API)	"github.com/gin-gonic/gin"	_ "prime-trade/task-service/docs"	"prime-trade/task-service/internal/services"	"prime-trade/task-service/internal/routes"	"prime-trade/task-service/internal/repositories"	"prime-trade/task-service/internal/models"	"prime-trade/task-service/internal/middleware"	"prime-trade/task-service/internal/controllers"	"prime-trade/task-service/internal/config"	"time"	"syscall"	"os/signal"	"os"	"net/http"	"log"	"context"import (package main